#
# Minimal docker-compose file for development.
#
# Bring up service using:
#   docker-compose up
#
version: "3.8"
services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      - DBA_PASSWORD=myDbaPassword
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.ndc.com/test-graph

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  backend:
    image: gcr.io/distroless/java:11-debug-nonroot
    restart: on-failure
    depends_on:
      - virtuoso
      - elasticsearch
    volumes:
      - ${PWD}/build/libs/:/jar
    command: [ "/jar/dati-semantic-backend-0.0.1-SNAPSHOT.jar" ]
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - VIRTUOSO_SPARQL_URL=http://virtuoso:8890/sparql
      - VIRTUOSO_SPARQL_GRAPH_STORE_URL=http://virtuoso:8890/sparql-graph-crud
      - HARVESTER_REPOSITORIES=https://github.com/ash1425/sample-ontology-repo

