openapi: 3.0.1
info:
  title: NDC Semantic Backend
  version: 0.0.1
  description: |-
    NDC Semantic Backend
  termsOfService: /tos
  contact:
    name: NDC Semantic Backend
    email: info@teamdigitale.governo.it
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  x-summary: NDC Semantic Backend
tags:
  - name: vocabulary-data-controller
    description: Entry point for Vocabulary related data
servers:
  - url: /
    description: Public server
paths:
  "/vocabularies/{agency_id}/{key_concept}":
    get:
      security: []
      tags:
        - vocabulary-data-controller
      operationId: fetchVocabularyData
      parameters:
        - name: agency_id
          in: path
          required: true
          schema:
            type: string
        - name: key_concept
          in: path
          required: true
          schema:
            type: string
        - name: offset
          in: query
          required: false
          schema:
            maximum: 30000
            minimum: 0
            type: integer
            format: int32
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            maximum: 200
            minimum: 1
            type: integer
            format: int32
            default: 10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VocabularyData"
  "/vocabularies/{agency_id}/{key_concept}/{id}":
    get:
      security: []
      tags:
        - vocabulary-data-controller
      operationId: fetchVocabularyItem
      parameters:
        - name: agency_id
          in: path
          required: true
          schema:
            type: string
        - name: key_concept
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
  /status:
    get:
      security: []
      tags:
        - application-status-controller
      operationId: getStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Health"
  /semantic-assets:
    get:
      security: []
      tags:
        - semantic-assets-controller
      operationId: search
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
            default: ''
        - name: offset
          in: query
          required: false
          schema:
            maximum: 30000
            minimum: 0
            type: integer
            format: int32
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            maximum: 200
            minimum: 1
            type: integer
            format: int32
            default: 10
        - name: type
          in: query
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
            default: [ ]
        - name: theme
          in: query
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
            default: [ ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
  /semantic-assets/byIri:
    get:
      security: []
      tags:
        - semantic-assets-controller
      operationId: getDetails
      parameters:
        - name: iri
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SemanticAssetDetailsDto"
components:
  schemas:
    VocabularyData:
      type: object
      properties:
        totalResults:
          type: integer
          format: int64
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int64
        data:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
    Health:
      type: object
      properties:
        status:
          type: integer
          format: int32
        title:
          type: string
    NodeSummary:
      type: object
      properties:
        iri:
          type: string
        summary:
          type: string
    SearchResult:
      type: object
      properties:
        totalCount:
          type: integer
          format: int64
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int64
        data:
          type: array
          items:
            $ref: "#/components/schemas/SearchResultItem"
    SearchResultItem:
      type: object
      properties:
        assetIri:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          $ref: "#/components/schemas/AssetType"
        modifiedOn:
          type: string
          format: date
        versionInfo:
          type: string
        themes:
          type: array
          items:
            type: string
        rightsHolder:
          $ref: "#/components/schemas/NodeSummary"
    SemanticAssetDetailsDto:
      type: object
      properties:
        assetIri:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          $ref: "#/components/schemas/AssetType"
        modifiedOn:
          type: string
          format: date
        themes:
          type: array
          items:
            type: string
        rightsHolder:
          $ref: "#/components/schemas/NodeSummary"
        accrualPeriodicity:
          type: string
        distributionUrls:
          type: array
          items:
            type: string
        subjects:
          type: array
          items:
            type: string
        contactPoint:
          $ref: "#/components/schemas/NodeSummary"
        publishers:
          type: array
          items:
            $ref: "#/components/schemas/NodeSummary"
        creators:
          type: array
          items:
            $ref: "#/components/schemas/NodeSummary"
        versionInfo:
          type: string
        issuedOn:
          type: string
          format: date
        languages:
          type: array
          items:
            type: string
        temporal:
          type: string
        conformsTo:
          type: array
          items:
            $ref: "#/components/schemas/NodeSummary"
        keyConcept:
          type: string
        endpointUrl:
          type: string
        keyClasses:
          type: array
          items:
            $ref: "#/components/schemas/NodeSummary"
        prefix:
          type: string
        projects:
          type: array
          items:
            $ref: "#/components/schemas/NodeSummary"
    AssetType:
      type: string
      enum:
        - ONTOLOGY
        - CONTROLLED_VOCABULARY
        - SCHEMA
